apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: wow
  labels:
    app: postgresql
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 5Gi

