apiVersion: v1
kind: ConfigMap
metadata:
  name: wow-frontend-env
  namespace: wow
data:
  NUXT_DB_AUTH_USER: "acore"
  NUXT_DB_AUTH_HOST: "wow-acore-auth-db"
  NUXT_DB_AUTH_PORT: "3306"
  NUXT_DB_REALM_0_ID: "1"
  NUXT_DB_REALM_0_NAME: "Azeroth WotLK"
  NUXT_DB_REALM_0_DESCRIPTION: "Blizzlike"
  NUXT_DB_REALM_0_USER: "acore"
  NUXT_DB_REALM_0_HOST: "wow-acore-blizzlike-db"
  NUXT_DB_REALM_0_PORT: "3306"
  NUXT_DB_REALM_0_SOAP_ENABLED: "true"
  NUXT_DB_REALM_0_SOAP_HOST: "wow-wotlk-blizzlike-soap"
  NUXT_DB_REALM_0_SOAP_PORT: "7878"
  NUXT_DB_REALM_0_SOAP_USERNAME: "daniel"
  NUXT_DB_REALM_1_ID: "2"
  NUXT_DB_REALM_1_NAME: "Individual Progression"
  NUXT_DB_REALM_1_DESCRIPTION: "Individual Progression Realm"
  NUXT_DB_REALM_1_USER: "acore"
  NUXT_DB_REALM_1_HOST: "wow-acore-ip-db"
  NUXT_DB_REALM_1_PORT: "3306"
  NUXT_DB_REALM_1_SOAP_ENABLED: "true"
  NUXT_DB_REALM_1_SOAP_HOST: "wow-wotlk-ip-soap"
  NUXT_DB_REALM_1_SOAP_PORT: "7878"
  NUXT_DB_REALM_1_SOAP_USERNAME: "daniel"
  NUXT_DB_REALM_2_ID: "3"
  NUXT_DB_REALM_2_NAME: "Individual Progression Boosted"
  NUXT_DB_REALM_2_DESCRIPTION: "Individual Progression with Boosted Rates Realm"
  NUXT_DB_REALM_2_USER: "acore"
  NUXT_DB_REALM_2_HOST: "wow-acore-ip-boosted-db"
  NUXT_DB_REALM_2_PORT: "3306"
  NUXT_DB_REALM_2_SOAP_ENABLED: "true"
  NUXT_DB_REALM_2_SOAP_HOST: "wow-wotlk-ip-boosted-soap"
  NUXT_DB_REALM_2_SOAP_PORT: "7878"
  NUXT_DB_REALM_2_SOAP_USERNAME: "daniel"
  NUXT_PUBLIC_KEYCLOAK_URL: "https://oauth2-user.dani-home.de?rd=https://wow-wotlk.dani-home.de"
  NUXT_PUBLIC_KEYCLOAK_REALM: "dani-home.de"
  NUXT_PUBLIC_KEYCLOAK_CLIENT_ID: "wow-frontend"
  NUXT_PUBLIC_APP_BASE_URL: "https://wow-wotlk.dani-home.de"
  NUXT_PUBLIC_SHOP_DELIVERY_METHOD: "both"
  NUXT_PUBLIC_SHOP_MARKUP_PERCENT: "20"
  NUXT_PUBLIC_AUTH_MODE: "oauth-proxy"
  NUXT_PUBLIC_DEBUG_MODE: "false"
