apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wow-frontend-sqllite-data
  namespace: wow
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wow-frontend-data
  namespace: wow
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 50Gi

