/**
 * Buff perks — Class buffs (aura-based, repeatable)
 *
 * Applied via Eluna player:AddAura()
 *
 * Each buff has multiple ranks keyed by requiredLevel.
 * Perks sharing the same rankGroup are alternative ranks —
 * the UI shows only the highest-level rank the character qualifies for.
 */

import type { PerkDefinition } from './types'

export const BUFF_PERKS: PerkDefinition[] = [
  // ── Druid: Mark of the Wild ──
  //  Single-target 1hr buff. Gift of the Wild (raid version) shares same rankGroup
  //  since only one should be shown.
  {
    id: 'buff-motw-r1',
    group: 'buffs',
    name: 'Mark of the Wild (Rank 1)',
    icon: '🌿',
    description: '+1 all attributes, +1 all resistances, +25 armor. Lasts 1 hour.',
    successMessage: 'Mark of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 1126,
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R1',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r2',
    group: 'buffs',
    name: 'Mark of the Wild (Rank 2)',
    icon: '🌿',
    description: '+2 all attributes, +1 all resistances, +65 armor. Lasts 1 hour.',
    successMessage: 'Mark of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 5232,
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 10,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R2',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r3',
    group: 'buffs',
    name: 'Mark of the Wild (Rank 3)',
    icon: '🌿',
    description: '+4 all attributes, +1 all resistances, +105 armor. Lasts 1 hour.',
    successMessage: 'Mark of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 6756,
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 20,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R3',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r4',
    group: 'buffs',
    name: 'Mark of the Wild (Rank 4)',
    icon: '🌿',
    description: '+6 all attributes, +5 all resistances, +150 armor. Lasts 1 hour.',
    successMessage: 'Mark of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 5234,
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R4',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r5',
    group: 'buffs',
    name: 'Mark of the Wild (Rank 5)',
    icon: '🌿',
    description: '+8 all attributes, +10 all resistances, +195 armor. Lasts 1 hour.',
    successMessage: 'Mark of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 8907,
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R5',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r6',
    group: 'buffs',
    name: 'Gift of the Wild (Rank 1)',
    icon: '🌿',
    description: '+10 all attributes, +15 all resistances, +240 armor. Lasts 1 hour.',
    successMessage: 'Gift of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 21849, // Gift of the Wild R1 = same stats as MotW R6
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R6',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r7',
    group: 'buffs',
    name: 'Gift of the Wild (Rank 2)',
    icon: '🌿',
    description: '+12 all attributes, +20 all resistances, +285 armor. Lasts 1 hour.',
    successMessage: 'Gift of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 21850, // Gift of the Wild R2
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R7',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r8',
    group: 'buffs',
    name: 'Gift of the Wild (Rank 3)',
    icon: '🌿',
    description: '+14 all attributes, +25 all resistances, +340 armor. Lasts 1 hour.',
    successMessage: 'Gift of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 26991, // Gift of the Wild R3
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW_R8',
    rankGroup: 'buff-motw',
  },
  {
    id: 'buff-motw-r9',
    group: 'buffs',
    name: 'Gift of the Wild (Rank 4)',
    icon: '🌿',
    description: '+37 all attributes, +54 all resistances, +750 armor. Lasts 1 hour.',
    successMessage: 'Gift of the Wild has been applied!',
    deliveryType: 'aura',
    gameId: 48470, // Gift of the Wild R4
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 80,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    envPrefix: 'BUFF_MOTW',
    rankGroup: 'buff-motw',
  },

  // ── Priest: Fortitude ──
  //  PW:Fortitude (single) → Prayer of Fortitude (raid) at higher levels
  {
    id: 'buff-fort-r1',
    group: 'buffs',
    name: 'Power Word: Fortitude (Rank 1)',
    icon: '🛡️',
    description: '+3 Stamina. Lasts 30 min.',
    successMessage: 'Power Word: Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 1243,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R1',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r2',
    group: 'buffs',
    name: 'Power Word: Fortitude (Rank 2)',
    icon: '🛡️',
    description: '+8 Stamina. Lasts 30 min.',
    successMessage: 'Power Word: Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 1244,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 12,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R2',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r3',
    group: 'buffs',
    name: 'Power Word: Fortitude (Rank 3)',
    icon: '🛡️',
    description: '+20 Stamina. Lasts 30 min.',
    successMessage: 'Power Word: Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 1245,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 24,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R3',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r4',
    group: 'buffs',
    name: 'Power Word: Fortitude (Rank 4)',
    icon: '🛡️',
    description: '+32 Stamina. Lasts 30 min.',
    successMessage: 'Power Word: Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 2791,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 36,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R4',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r5',
    group: 'buffs',
    name: 'Prayer of Fortitude (Rank 1)',
    icon: '🛡️',
    description: '+43 Stamina. Lasts 1 hour.',
    successMessage: 'Prayer of Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 21562, // Prayer of Fortitude R1
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 48,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R5',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r6',
    group: 'buffs',
    name: 'Prayer of Fortitude (Rank 2)',
    icon: '🛡️',
    description: '+54 Stamina. Lasts 1 hour.',
    successMessage: 'Prayer of Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 21564, // Prayer of Fortitude R2
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R6',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r7',
    group: 'buffs',
    name: 'Prayer of Fortitude (Rank 3)',
    icon: '🛡️',
    description: '+79 Stamina. Lasts 1 hour.',
    successMessage: 'Prayer of Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 25392, // Prayer of Fortitude R3
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT_R7',
    rankGroup: 'buff-fort',
  },
  {
    id: 'buff-fort-r8',
    group: 'buffs',
    name: 'Prayer of Fortitude (Rank 4)',
    icon: '🛡️',
    description: '+165 Stamina. Lasts 1 hour.',
    successMessage: 'Prayer of Fortitude has been applied!',
    deliveryType: 'aura',
    gameId: 48162, // Prayer of Fortitude R4
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 80,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_FORT',
    rankGroup: 'buff-fort',
  },

  // ── Priest: Divine Spirit / Prayer of Spirit ──
  {
    id: 'buff-spirit-r1',
    group: 'buffs',
    name: 'Divine Spirit (Rank 1)',
    icon: '💫',
    description: '+17 Spirit. Lasts 30 min.',
    successMessage: 'Divine Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 14752,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT_R1',
    rankGroup: 'buff-spirit',
  },
  {
    id: 'buff-spirit-r2',
    group: 'buffs',
    name: 'Divine Spirit (Rank 2)',
    icon: '💫',
    description: '+23 Spirit. Lasts 30 min.',
    successMessage: 'Divine Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 14818,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT_R2',
    rankGroup: 'buff-spirit',
  },
  {
    id: 'buff-spirit-r3',
    group: 'buffs',
    name: 'Divine Spirit (Rank 3)',
    icon: '💫',
    description: '+33 Spirit. Lasts 30 min.',
    successMessage: 'Divine Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 14819,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT_R3',
    rankGroup: 'buff-spirit',
  },
  {
    id: 'buff-spirit-r4',
    group: 'buffs',
    name: 'Prayer of Spirit (Rank 1)',
    icon: '💫',
    description: '+40 Spirit. Lasts 1 hour.',
    successMessage: 'Prayer of Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 27681, // Prayer of Spirit R1
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT_R4',
    rankGroup: 'buff-spirit',
  },
  {
    id: 'buff-spirit-r5',
    group: 'buffs',
    name: 'Prayer of Spirit (Rank 2)',
    icon: '💫',
    description: '+50 Spirit. Lasts 1 hour.',
    successMessage: 'Prayer of Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 32999, // Prayer of Spirit R2
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT_R5',
    rankGroup: 'buff-spirit',
  },
  {
    id: 'buff-spirit-r6',
    group: 'buffs',
    name: 'Prayer of Spirit (Rank 3)',
    icon: '💫',
    description: '+80 Spirit. Lasts 1 hour.',
    successMessage: 'Prayer of Spirit has been applied!',
    deliveryType: 'aura',
    gameId: 48074, // Prayer of Spirit R3
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 80,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_SPIRIT',
    rankGroup: 'buff-spirit',
  },

  // ── Priest: Shadow Protection / Prayer of Shadow Protection ──
  {
    id: 'buff-shadow-prot-r1',
    group: 'buffs',
    name: 'Shadow Protection (Rank 1)',
    icon: '🌑',
    description: '+30 Shadow Resistance. Lasts 10 min.',
    successMessage: 'Shadow Protection has been applied!',
    deliveryType: 'aura',
    gameId: 976,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    envPrefix: 'BUFF_SHADOW_PROT_R1',
    rankGroup: 'buff-shadow-prot',
  },
  {
    id: 'buff-shadow-prot-r2',
    group: 'buffs',
    name: 'Shadow Protection (Rank 2)',
    icon: '🌑',
    description: '+45 Shadow Resistance. Lasts 10 min.',
    successMessage: 'Shadow Protection has been applied!',
    deliveryType: 'aura',
    gameId: 10957,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 42,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    envPrefix: 'BUFF_SHADOW_PROT_R2',
    rankGroup: 'buff-shadow-prot',
  },
  {
    id: 'buff-shadow-prot-r3',
    group: 'buffs',
    name: 'Prayer of Shadow Protection (Rank 1)',
    icon: '🌑',
    description: '+60 Shadow Resistance. Lasts 20 min.',
    successMessage: 'Prayer of Shadow Protection has been applied!',
    deliveryType: 'aura',
    gameId: 27683, // Prayer of Shadow Prot R1
    auraDurationMs: 1200000,
    failDebuffDurationMs: 1200000,
    requiredLevel: 56,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    envPrefix: 'BUFF_SHADOW_PROT_R3',
    rankGroup: 'buff-shadow-prot',
  },
  {
    id: 'buff-shadow-prot-r4',
    group: 'buffs',
    name: 'Shadow Protection (Rank 4)',
    icon: '🌑',
    description: '+70 Shadow Resistance. Lasts 10 min.',
    successMessage: 'Shadow Protection has been applied!',
    deliveryType: 'aura',
    gameId: 25433,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 68,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    envPrefix: 'BUFF_SHADOW_PROT_R4',
    rankGroup: 'buff-shadow-prot',
  },
  {
    id: 'buff-shadow-prot-r5',
    group: 'buffs',
    name: 'Prayer of Shadow Protection (Rank 2)',
    icon: '🌑',
    description: '+130 Shadow Resistance. Lasts 20 min.',
    successMessage: 'Prayer of Shadow Protection has been applied!',
    deliveryType: 'aura',
    gameId: 48170, // Prayer of Shadow Prot R3
    auraDurationMs: 1200000,
    failDebuffDurationMs: 1200000,
    requiredLevel: 77,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    envPrefix: 'BUFF_SHADOW_PROT',
    rankGroup: 'buff-shadow-prot',
  },

  // ── Mage: Arcane Intellect / Arcane Brilliance ──
  {
    id: 'buff-ai-r1',
    group: 'buffs',
    name: 'Arcane Intellect (Rank 1)',
    icon: '🔮',
    description: '+2 Intellect. Lasts 30 min.',
    successMessage: 'Arcane Intellect has been applied!',
    deliveryType: 'aura',
    gameId: 1459,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R1',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r2',
    group: 'buffs',
    name: 'Arcane Intellect (Rank 2)',
    icon: '🔮',
    description: '+7 Intellect. Lasts 30 min.',
    successMessage: 'Arcane Intellect has been applied!',
    deliveryType: 'aura',
    gameId: 1460,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 14,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R2',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r3',
    group: 'buffs',
    name: 'Arcane Intellect (Rank 3)',
    icon: '🔮',
    description: '+15 Intellect. Lasts 30 min.',
    successMessage: 'Arcane Intellect has been applied!',
    deliveryType: 'aura',
    gameId: 1461,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 28,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R3',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r4',
    group: 'buffs',
    name: 'Arcane Intellect (Rank 4)',
    icon: '🔮',
    description: '+22 Intellect. Lasts 30 min.',
    successMessage: 'Arcane Intellect has been applied!',
    deliveryType: 'aura',
    gameId: 10156,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 42,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R4',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r5',
    group: 'buffs',
    name: 'Arcane Brilliance (Rank 1)',
    icon: '🔮',
    description: '+31 Intellect. Lasts 1 hour.',
    successMessage: 'Arcane Brilliance has been applied!',
    deliveryType: 'aura',
    gameId: 23028, // Arcane Brilliance R1
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 56,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R5',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r6',
    group: 'buffs',
    name: 'Arcane Brilliance (Rank 2)',
    icon: '🔮',
    description: '+40 Intellect. Lasts 1 hour.',
    successMessage: 'Arcane Brilliance has been applied!',
    deliveryType: 'aura',
    gameId: 27127, // Arcane Brilliance R2
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI_R6',
    rankGroup: 'buff-ai',
  },
  {
    id: 'buff-ai-r7',
    group: 'buffs',
    name: 'Arcane Brilliance (Rank 3)',
    icon: '🔮',
    description: '+60 Intellect. Lasts 1 hour.',
    successMessage: 'Arcane Brilliance has been applied!',
    deliveryType: 'aura',
    gameId: 43002, // Arcane Brilliance R3
    auraDurationMs: 3600000,
    failDebuffDurationMs: 3600000,
    requiredLevel: 80,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_AI',
    rankGroup: 'buff-ai',
  },

  // ── Paladin: Blessing of Kings ──
  //  Only 1 rank (10% stats) — Greater version at 60
  {
    id: 'buff-kings-r1',
    group: 'buffs',
    name: 'Blessing of Kings',
    icon: '👑',
    description: '+10% all stats. Lasts 10 min.',
    successMessage: 'Blessing of Kings has been applied!',
    deliveryType: 'aura',
    gameId: 20217,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 20,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'orange',
    envPrefix: 'BUFF_KINGS_R1',
    rankGroup: 'buff-kings',
  },
  {
    id: 'buff-kings-r2',
    group: 'buffs',
    name: 'Greater Blessing of Kings',
    icon: '👑',
    description: '+10% all stats. Lasts 30 min.',
    successMessage: 'Greater Blessing of Kings has been applied!',
    deliveryType: 'aura',
    gameId: 25898,
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'orange',
    envPrefix: 'BUFF_KINGS',
    rankGroup: 'buff-kings',
  },

  // ── Paladin: Blessing of Might ──
  {
    id: 'buff-might-r1',
    group: 'buffs',
    name: 'Blessing of Might (Rank 1)',
    icon: '⚔️',
    description: '+20 Attack Power. Lasts 10 min.',
    successMessage: 'Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 19740,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R1',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r2',
    group: 'buffs',
    name: 'Blessing of Might (Rank 2)',
    icon: '⚔️',
    description: '+35 Attack Power. Lasts 10 min.',
    successMessage: 'Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 19834,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 12,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R2',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r3',
    group: 'buffs',
    name: 'Blessing of Might (Rank 3)',
    icon: '⚔️',
    description: '+55 Attack Power. Lasts 10 min.',
    successMessage: 'Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 19835,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 22,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R3',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r4',
    group: 'buffs',
    name: 'Blessing of Might (Rank 4)',
    icon: '⚔️',
    description: '+85 Attack Power. Lasts 10 min.',
    successMessage: 'Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 19836,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 32,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R4',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r5',
    group: 'buffs',
    name: 'Blessing of Might (Rank 5)',
    icon: '⚔️',
    description: '+130 Attack Power. Lasts 10 min.',
    successMessage: 'Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 19837,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 42,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R5',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r6',
    group: 'buffs',
    name: 'Greater Blessing of Might (Rank 1)',
    icon: '⚔️',
    description: '+185 Attack Power. Lasts 30 min.',
    successMessage: 'Greater Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 25782, // Greater BoM R1
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 52,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R6',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r7',
    group: 'buffs',
    name: 'Greater Blessing of Might (Rank 2)',
    icon: '⚔️',
    description: '+232 Attack Power. Lasts 30 min.',
    successMessage: 'Greater Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 25916, // Greater BoM R2
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R7',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r8',
    group: 'buffs',
    name: 'Greater Blessing of Might (Rank 3)',
    icon: '⚔️',
    description: '+306 Attack Power. Lasts 30 min.',
    successMessage: 'Greater Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 27141, // Greater BoM R3
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT_R8',
    rankGroup: 'buff-might',
  },
  {
    id: 'buff-might-r9',
    group: 'buffs',
    name: 'Greater Blessing of Might (Rank 5)',
    icon: '⚔️',
    description: '+550 Attack Power. Lasts 30 min.',
    successMessage: 'Greater Blessing of Might has been applied!',
    deliveryType: 'aura',
    gameId: 48934, // Greater BoM R5
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 79,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    envPrefix: 'BUFF_MIGHT',
    rankGroup: 'buff-might',
  },

  // ── Paladin: Blessing of Wisdom ──
  {
    id: 'buff-wisdom-r1',
    group: 'buffs',
    name: 'Blessing of Wisdom (Rank 1)',
    icon: '📘',
    description: '+10 mana per 5 sec. Lasts 10 min.',
    successMessage: 'Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 19742,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 14,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R1',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r2',
    group: 'buffs',
    name: 'Blessing of Wisdom (Rank 2)',
    icon: '📘',
    description: '+15 mana per 5 sec. Lasts 10 min.',
    successMessage: 'Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 19850,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 24,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R2',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r3',
    group: 'buffs',
    name: 'Blessing of Wisdom (Rank 3)',
    icon: '📘',
    description: '+20 mana per 5 sec. Lasts 10 min.',
    successMessage: 'Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 19852,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 34,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R3',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r4',
    group: 'buffs',
    name: 'Blessing of Wisdom (Rank 4)',
    icon: '📘',
    description: '+25 mana per 5 sec. Lasts 10 min.',
    successMessage: 'Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 19853,
    auraDurationMs: 600000,
    failDebuffDurationMs: 600000,
    requiredLevel: 44,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R4',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r5',
    group: 'buffs',
    name: 'Greater Blessing of Wisdom (Rank 1)',
    icon: '📘',
    description: '+30 mana per 5 sec. Lasts 30 min.',
    successMessage: 'Greater Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 25894, // Greater BoW R1
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 54,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R5',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r6',
    group: 'buffs',
    name: 'Greater Blessing of Wisdom (Rank 2)',
    icon: '📘',
    description: '+33 mana per 5 sec. Lasts 30 min.',
    successMessage: 'Greater Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 25918, // Greater BoW R2
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R6',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r7',
    group: 'buffs',
    name: 'Greater Blessing of Wisdom (Rank 3)',
    icon: '📘',
    description: '+41 mana per 5 sec. Lasts 30 min.',
    successMessage: 'Greater Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 27143, // Greater BoW R3
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 65,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM_R7',
    rankGroup: 'buff-wisdom',
  },
  {
    id: 'buff-wisdom-r8',
    group: 'buffs',
    name: 'Greater Blessing of Wisdom (Rank 5)',
    icon: '📘',
    description: '+92 mana per 5 sec. Lasts 30 min.',
    successMessage: 'Greater Blessing of Wisdom has been applied!',
    deliveryType: 'aura',
    gameId: 48938, // Greater BoW R5
    auraDurationMs: 1800000,
    failDebuffDurationMs: 1800000,
    requiredLevel: 77,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    envPrefix: 'BUFF_WISDOM',
    rankGroup: 'buff-wisdom',
  },
]
