/**
 * Scroll perks — Stat scrolls (bag-item delivery, repeatable)
 *
 * Delivered directly to character's bags via web_bag_requests.
 *
 * Tiers I–VIII: level requirement scales with tier
 *   I = any level, II = 15, III = 30, IV = 40, V = 50, VI–VII = 60, VIII = 70
 * Lower tiers are easier rolls (d4 threshold 2) with higher daily limits (10).
 * Higher tiers are harder (d6 threshold 2) with lower daily limits (3–5).
 */

import type { PerkDefinition } from './types'

export const SCROLL_PERKS: PerkDefinition[] = [
  // ── Intellect ──
  {
    id: 'scroll-intellect-i',
    group: 'scrolls',
    name: 'Scroll of Intellect I',
    icon: '📜',
    description: '+3 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 955,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect I',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_I',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-ii',
    group: 'scrolls',
    name: 'Scroll of Intellect II',
    icon: '📜',
    description: '+5 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 2290,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect II',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_II',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-iii',
    group: 'scrolls',
    name: 'Scroll of Intellect III',
    icon: '📜',
    description: '+12 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4419,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect III',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_III',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-iv',
    group: 'scrolls',
    name: 'Scroll of Intellect IV',
    icon: '📜',
    description: '+17 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10308,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect IV',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_IV',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-v',
    group: 'scrolls',
    name: 'Scroll of Intellect V',
    icon: '📜',
    description: '+21 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27499,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect V',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_V',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-vi',
    group: 'scrolls',
    name: 'Scroll of Intellect VI',
    icon: '📜',
    description: '+24 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33458,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect VI',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_VI',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-vii',
    group: 'scrolls',
    name: 'Scroll of Intellect VII',
    icon: '📜',
    description: '+32 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37091,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect VII',
    mailBody: 'A scroll of power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_VII',
    rankGroup: 'scroll-int',
  },
  {
    id: 'scroll-intellect-viii',
    group: 'scrolls',
    name: 'Scroll of Intellect VIII',
    icon: '📜',
    description: '+48 Intellect for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Intellect VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37092,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'blue',
    mailSubject: 'Scroll of Intellect VIII',
    mailBody: 'A scroll of greater power arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_INT_VIII',
    rankGroup: 'scroll-int',
  },

  // ── Strength ──
  {
    id: 'scroll-strength-i',
    group: 'scrolls',
    name: 'Scroll of Strength I',
    icon: '📜',
    description: '+3 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 954,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'red',
    mailSubject: 'Scroll of Strength I',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_I',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-ii',
    group: 'scrolls',
    name: 'Scroll of Strength II',
    icon: '📜',
    description: '+5 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 2289,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'red',
    mailSubject: 'Scroll of Strength II',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_II',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-iii',
    group: 'scrolls',
    name: 'Scroll of Strength III',
    icon: '📜',
    description: '+8 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4426,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'red',
    mailSubject: 'Scroll of Strength III',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_III',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-iv',
    group: 'scrolls',
    name: 'Scroll of Strength IV',
    icon: '📜',
    description: '+10 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10310,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'red',
    mailSubject: 'Scroll of Strength IV',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_IV',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-v',
    group: 'scrolls',
    name: 'Scroll of Strength V',
    icon: '📜',
    description: '+15 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27503,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'red',
    mailSubject: 'Scroll of Strength V',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_V',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-vi',
    group: 'scrolls',
    name: 'Scroll of Strength VI',
    icon: '📜',
    description: '+20 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33462,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'red',
    mailSubject: 'Scroll of Strength VI',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_VI',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-vii',
    group: 'scrolls',
    name: 'Scroll of Strength VII',
    icon: '📜',
    description: '+25 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43465,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'red',
    mailSubject: 'Scroll of Strength VII',
    mailBody: 'A scroll of might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_VII',
    rankGroup: 'scroll-str',
  },
  {
    id: 'scroll-strength-viii',
    group: 'scrolls',
    name: 'Scroll of Strength VIII',
    icon: '📜',
    description: '+30 Strength for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Strength VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43466,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'red',
    mailSubject: 'Scroll of Strength VIII',
    mailBody: 'A scroll of greater might arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STR_VIII',
    rankGroup: 'scroll-str',
  },

  // ── Agility ──
  {
    id: 'scroll-agility-i',
    group: 'scrolls',
    name: 'Scroll of Agility I',
    icon: '📜',
    description: '+3 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 3012,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'green',
    mailSubject: 'Scroll of Agility I',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_I',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-ii',
    group: 'scrolls',
    name: 'Scroll of Agility II',
    icon: '📜',
    description: '+5 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1477,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'green',
    mailSubject: 'Scroll of Agility II',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_II',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-iii',
    group: 'scrolls',
    name: 'Scroll of Agility III',
    icon: '📜',
    description: '+8 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4425,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'green',
    mailSubject: 'Scroll of Agility III',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_III',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-iv',
    group: 'scrolls',
    name: 'Scroll of Agility IV',
    icon: '📜',
    description: '+10 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10309,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'green',
    mailSubject: 'Scroll of Agility IV',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_IV',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-v',
    group: 'scrolls',
    name: 'Scroll of Agility V',
    icon: '📜',
    description: '+15 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27498,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'green',
    mailSubject: 'Scroll of Agility V',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_V',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-vi',
    group: 'scrolls',
    name: 'Scroll of Agility VI',
    icon: '📜',
    description: '+20 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33457,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'green',
    mailSubject: 'Scroll of Agility VI',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_VI',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-vii',
    group: 'scrolls',
    name: 'Scroll of Agility VII',
    icon: '📜',
    description: '+25 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43463,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'green',
    mailSubject: 'Scroll of Agility VII',
    mailBody: 'A scroll of swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_VII',
    rankGroup: 'scroll-agi',
  },
  {
    id: 'scroll-agility-viii',
    group: 'scrolls',
    name: 'Scroll of Agility VIII',
    icon: '📜',
    description: '+30 Agility for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Agility VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43464,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'green',
    mailSubject: 'Scroll of Agility VIII',
    mailBody: 'A scroll of greater swiftness arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_AGI_VIII',
    rankGroup: 'scroll-agi',
  },

  // ── Stamina ──
  {
    id: 'scroll-stamina-i',
    group: 'scrolls',
    name: 'Scroll of Stamina I',
    icon: '📜',
    description: '+3 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1180,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina I',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_I',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-ii',
    group: 'scrolls',
    name: 'Scroll of Stamina II',
    icon: '📜',
    description: '+5 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1711,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina II',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_II',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-iii',
    group: 'scrolls',
    name: 'Scroll of Stamina III',
    icon: '📜',
    description: '+16 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4422,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina III',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_III',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-iv',
    group: 'scrolls',
    name: 'Scroll of Stamina IV',
    icon: '📜',
    description: '+25 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10307,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina IV',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_IV',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-v',
    group: 'scrolls',
    name: 'Scroll of Stamina V',
    icon: '📜',
    description: '+34 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27502,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina V',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_V',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-vi',
    group: 'scrolls',
    name: 'Scroll of Stamina VI',
    icon: '📜',
    description: '+43 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33461,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina VI',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_VI',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-vii',
    group: 'scrolls',
    name: 'Scroll of Stamina VII',
    icon: '📜',
    description: '+63 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37093,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina VII',
    mailBody: 'A scroll of vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_VII',
    rankGroup: 'scroll-sta',
  },
  {
    id: 'scroll-stamina-viii',
    group: 'scrolls',
    name: 'Scroll of Stamina VIII',
    icon: '📜',
    description: '+132 Stamina for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Stamina VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37094,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'orange',
    mailSubject: 'Scroll of Stamina VIII',
    mailBody: 'A scroll of greater vitality arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_STA_VIII',
    rankGroup: 'scroll-sta',
  },

  // ── Spirit ──
  {
    id: 'scroll-spirit-i',
    group: 'scrolls',
    name: 'Scroll of Spirit I',
    icon: '📜',
    description: '+3 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1181,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit I',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_I',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-ii',
    group: 'scrolls',
    name: 'Scroll of Spirit II',
    icon: '📜',
    description: '+5 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1712,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit II',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_II',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-iii',
    group: 'scrolls',
    name: 'Scroll of Spirit III',
    icon: '📜',
    description: '+13 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4424,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit III',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_III',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-iv',
    group: 'scrolls',
    name: 'Scroll of Spirit IV',
    icon: '📜',
    description: '+18 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10306,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit IV',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_IV',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-v',
    group: 'scrolls',
    name: 'Scroll of Spirit V',
    icon: '📜',
    description: '+26 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27501,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit V',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_V',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-vi',
    group: 'scrolls',
    name: 'Scroll of Spirit VI',
    icon: '📜',
    description: '+32 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33460,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit VI',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_VI',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-vii',
    group: 'scrolls',
    name: 'Scroll of Spirit VII',
    icon: '📜',
    description: '+40 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37097,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit VII',
    mailBody: 'A scroll of enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_VII',
    rankGroup: 'scroll-spi',
  },
  {
    id: 'scroll-spirit-viii',
    group: 'scrolls',
    name: 'Scroll of Spirit VIII',
    icon: '📜',
    description: '+64 Spirit for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Spirit VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 37098,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'purple',
    mailSubject: 'Scroll of Spirit VIII',
    mailBody: 'A scroll of greater enlightenment arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_SPI_VIII',
    rankGroup: 'scroll-spi',
  },

  // ── Protection (Armor) ──
  {
    id: 'scroll-protection-i',
    group: 'scrolls',
    name: 'Scroll of Protection I',
    icon: '📜',
    description: '+65 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection I has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 3013,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Protection I',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_I',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-ii',
    group: 'scrolls',
    name: 'Scroll of Protection II',
    icon: '📜',
    description: '+105 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection II has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 1478,
    requiredLevel: 15,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Protection II',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_II',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-iii',
    group: 'scrolls',
    name: 'Scroll of Protection III',
    icon: '📜',
    description: '+150 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection III has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 4421,
    requiredLevel: 30,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 10,
    accent: 'orange',
    mailSubject: 'Scroll of Protection III',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_III',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-iv',
    group: 'scrolls',
    name: 'Scroll of Protection IV',
    icon: '📜',
    description: '+195 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection IV has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 10305,
    requiredLevel: 40,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'orange',
    mailSubject: 'Scroll of Protection IV',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_IV',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-v',
    group: 'scrolls',
    name: 'Scroll of Protection V',
    icon: '📜',
    description: '+240 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection V has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 27500,
    requiredLevel: 50,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 8,
    accent: 'orange',
    mailSubject: 'Scroll of Protection V',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_V',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-vi',
    group: 'scrolls',
    name: 'Scroll of Protection VI',
    icon: '📜',
    description: '+285 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection VI has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 33459,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    mailSubject: 'Scroll of Protection VI',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_VI',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-vii',
    group: 'scrolls',
    name: 'Scroll of Protection VII',
    icon: '📜',
    description: '+340 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection VII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43467,
    requiredLevel: 60,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 4,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    mailSubject: 'Scroll of Protection VII',
    mailBody: 'A scroll of warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_VII',
    rankGroup: 'scroll-prot',
  },
  {
    id: 'scroll-protection-viii',
    group: 'scrolls',
    name: 'Scroll of Protection VIII',
    icon: '📜',
    description: '+750 Armor for 30 min. Delivered directly to your bags.',
    successMessage: 'Scroll of Protection VIII has been delivered to your bags!',
    deliveryType: 'bag-item',
    gameId: 43468,
    requiredLevel: 70,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 3,
    accent: 'orange',
    mailSubject: 'Scroll of Protection VIII',
    mailBody: 'A scroll of greater warding arrives for you, hero.',
    itemCount: 5,
    envPrefix: 'SCROLL_PROT_VIII',
    rankGroup: 'scroll-prot',
  },
]
