/**
 * Teleport perks — Major city teleports
 *
 * Delivered via Eluna player:Teleport()
 * All require online. Repeatable.
 */

import type { PerkDefinition } from './types'

export const TELEPORT_PERKS: PerkDefinition[] = [
  // ── Alliance Cities ──
  {
    id: 'teleport-stormwind',
    group: 'teleport',
    name: 'Teleport: Stormwind',
    icon: '🏰',
    description: 'Teleport to Stormwind City, the human capital.',
    successMessage: 'You are being teleported to Stormwind City!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'blue',
    envPrefix: 'TP_STORMWIND',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 0,
    teleportX: -8833.38,
    teleportY: 628.62,
    teleportZ: 94.00,
    teleportO: 0,
  },
  {
    id: 'teleport-ironforge',
    group: 'teleport',
    name: 'Teleport: Ironforge',
    icon: '⛏️',
    description: 'Teleport to Ironforge, the dwarven stronghold.',
    successMessage: 'You are being teleported to Ironforge!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    envPrefix: 'TP_IRONFORGE',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 0,
    teleportX: -4918.88,
    teleportY: -940.41,
    teleportZ: 501.56,
    teleportO: 0,
  },
  {
    id: 'teleport-darnassus',
    group: 'teleport',
    name: 'Teleport: Darnassus',
    icon: '🌳',
    description: 'Teleport to Darnassus, the night elf capital.',
    successMessage: 'You are being teleported to Darnassus!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'purple',
    envPrefix: 'TP_DARNASSUS',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 1,
    teleportX: 9951.52,
    teleportY: 2280.32,
    teleportZ: 1341.39,
    teleportO: 0,
  },
  {
    id: 'teleport-exodar',
    group: 'teleport',
    name: 'Teleport: The Exodar',
    icon: '💎',
    description: 'Teleport to The Exodar, the draenei capital.',
    successMessage: 'You are being teleported to The Exodar!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'blue',
    envPrefix: 'TP_EXODAR',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 530,
    teleportX: -3965.7,
    teleportY: -11653.6,
    teleportZ: -138.84,
    teleportO: 0,
  },

  // ── Horde Cities ──
  {
    id: 'teleport-orgrimmar',
    group: 'teleport',
    name: 'Teleport: Orgrimmar',
    icon: '🔥',
    description: 'Teleport to Orgrimmar, the orcish capital.',
    successMessage: 'You are being teleported to Orgrimmar!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'red',
    envPrefix: 'TP_ORGRIMMAR',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 1,
    teleportX: 1676.21,
    teleportY: -4315.29,
    teleportZ: 61.52,
    teleportO: 0,
  },
  {
    id: 'teleport-thunder-bluff',
    group: 'teleport',
    name: 'Teleport: Thunder Bluff',
    icon: '🦬',
    description: 'Teleport to Thunder Bluff, the tauren capital.',
    successMessage: 'You are being teleported to Thunder Bluff!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    envPrefix: 'TP_THUNDER_BLUFF',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 1,
    teleportX: -1274.45,
    teleportY: 71.86,
    teleportZ: 128.16,
    teleportO: 0,
  },
  {
    id: 'teleport-undercity',
    group: 'teleport',
    name: 'Teleport: Undercity',
    icon: '💀',
    description: 'Teleport to the Undercity, the Forsaken capital.',
    successMessage: 'You are being teleported to the Undercity!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'purple',
    envPrefix: 'TP_UNDERCITY',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 0,
    teleportX: 1586.48,
    teleportY: 239.56,
    teleportZ: -52.15,
    teleportO: 0,
  },
  {
    id: 'teleport-silvermoon',
    group: 'teleport',
    name: 'Teleport: Silvermoon City',
    icon: '🌅',
    description: 'Teleport to Silvermoon City, the blood elf capital.',
    successMessage: 'You are being teleported to Silvermoon City!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 0,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'red',
    envPrefix: 'TP_SILVERMOON',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 530,
    teleportX: 9473.03,
    teleportY: -7279.67,
    teleportZ: 14.21,
    teleportO: 0,
  },

  // ── Neutral Cities ──
  {
    id: 'teleport-shattrath',
    group: 'teleport',
    name: 'Teleport: Shattrath City',
    icon: '☀️',
    description: 'Teleport to Shattrath City, the neutral hub of Outland.',
    successMessage: 'You are being teleported to Shattrath City!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 58,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'orange',
    envPrefix: 'TP_SHATTRATH',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 530,
    teleportX: -1838.16,
    teleportY: 5301.89,
    teleportZ: -12.43,
    teleportO: 0,
  },
  {
    id: 'teleport-dalaran',
    group: 'teleport',
    name: 'Teleport: Dalaran',
    icon: '🔮',
    description: 'Teleport to Dalaran, the floating city of Northrend.',
    successMessage: 'You are being teleported to Dalaran!',
    deliveryType: 'teleport',
    gameId: 0,
    requiredLevel: 68,
    requiresOnline: true,
    oneTime: false,
    defaultDiceSides: 6,
    defaultRollThreshold: 2,
    defaultDailyLimit: 5,
    accent: 'purple',
    envPrefix: 'TP_DALARAN',
    failDebuffSpellId: 1604,
    failDebuffDurationMs: 60000,
    teleportMapId: 571,
    teleportX: 5804.14,
    teleportY: 624.77,
    teleportZ: 647.77,
    teleportO: 0,
  },
]
